[package]
name = "rust-learning-parser-combinators"
version = "0.1.0"
authors = ["swiftaff <swiftaff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
